### ISSUE TITLE
Static Page: Augment /resources/ with text found in soybase.org/soymap2/species_sequenced.php, make links to it from /projects/

### ISSUE THREAD

**Issue by jd-campbell** [soybase/jekyll-soybase#58]

**Comment by jd-campbell** [comment]
@maxglycine and @StevenCannon-USDA 

From what I understand from the title of this Protect task is that we need to move the general text and images from https://soybase.org/soymap2/species_sequenced.php to https://dev.soybase.org/projects/zhuang_wang_2022/.

But I am not sure if this can be done. Because the project pages are created by a project_index plate and all the info is stored in a yaml file. 

So my question is for **Steven:** 
Can we make a similar page to  https://soybase.org/soymap2/species_sequenced.php and have it linked to the SoyMapII project page?

**Comment by StevenCannon-USDA** [comment]
Anything can be done :-)
But I am not sure exactly what the objective is.

To a large extent, I think the "resources" page (https://dev.soybase.org/resources/) meets the objective. I mean: most of the content from the soymap2 is available in the resources page, including the species descriptions, the pictures, links to the browsers, etc.

And the current projects page (https://dev.soybase.org/projects/zhuang_wang_2022/) gives the publications and the project history.

So, we may be done with this one. But if there are particular things missing, then let's fix those. For example, we can link from the resources page back to /projects/zhuang_wang_2022/ if you want. We would do that by changing the yaml in this file: https://data.legumeinfo.org/Glycine/GENUS/about_this_collection/description_Glycine.yml

**Comment by jd-campbell** [comment]
I agree that the https://dev.soybase.org/resources/ meets this objective.  Is there a way to link the https://dev.soybase.org/resources/ to the https://dev.soybase.org/projects/zhuang_wang_2022/ page so that users can easily find this info.

**Comment by StevenCannon-USDA** [comment]
@jd-campbell - yes, good idea (sorry to be slow).

Yes, we would add a block to https://data.legumeinfo.org/Glycine/GENUS/about_this_collection/description_Glycine.yml
Something like this:
```
  - name: SoyMap II project
    URL: "/projects/zhuang_wang_2022"
    description: "SoyMap II project to sequence diploid relatives of soybean."
```
and also in the species files, e.g., https://data.legumeinfo.org/Glycine/cyrtoloba/about_this_collection/description_Glycine_cyrtoloba.yml 
We do have something referring to SoyMap2, but you could add another block that links back to the project page.
```
resources:
  - name: SoyMap2 Diversity Browser on Gmax1.01
    URL: "https://soybase.org/gb2/gbrowse/gmax1.01/?label=diversity_cyrtoloba_BES_alignments_relaxed_filtering"
    description: "GBrowse for G. cyrtoloba Bac End Sequence alignments on Gmax1.01"
  - name: SoyMap2 Diversity Browser on Gmax2.0
    URL: "https://soybase.org/gb2/gbrowse/gmax2.0/?label=diversity_cyrtoloba_bes_alignments_relaxed_filtering"
    description: "GBrowse for G. cyrtoloba Bac End Sequence alignments on Gmax2.0"
```
